#ifndef COMPAT_AUTOCONF_INCLUDED
#define COMPAT_AUTOCONF_INCLUDED
/*
 * Automatically generated C config: don't edit
 * Fri Jan  4 00:01:14 EST 2013 
 * compat-wireless-2.6: 
 * linux-2.6: 
 */
#define COMPAT_RELEASE ""
#define COMPAT_KERNEL_RELEASE ""
#if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,24))
#error Compat-wireless requirement: Linux >= 2,6,24
#endif /* (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,24) */ 
#if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,24))
#endif /* CONFIG_COMPAT_KERNEL_2_6_24 */
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,27))
#endif /* CONFIG_COMPAT_KERNEL_2_6_27 */
#if (LINUX_VERSION_CODE < KERNEL_VERSION(2,6,33))
#if defined(CONFIG_FW_LOADER) || defined(CONFIG_FW_LOADER_MODULE)
#endif /* CONFIG_FW_LOADER */
#endif /* CONFIG_COMPAT_KERNEL_2_6_33 */
#ifndef CONFIG_BT
#define CONFIG_BT 1
#endif /* CONFIG_BT */ 
#ifndef CONFIG_COMPAT_BT_L2CAP
#define CONFIG_COMPAT_BT_L2CAP 1
#endif /* CONFIG_COMPAT_BT_L2CAP */ 
#ifndef CONFIG_COMPAT_BT_SCO
#define CONFIG_COMPAT_BT_SCO 1
#endif /* CONFIG_COMPAT_BT_SCO */ 
#ifndef CONFIG_BT_RFCOMM
#define CONFIG_BT_RFCOMM 1
#endif /* CONFIG_BT_RFCOMM */ 
#ifndef CONFIG_BT_RFCOMM_TTY
#define CONFIG_BT_RFCOMM_TTY 1
#endif /* CONFIG_BT_RFCOMM_TTY */ 
#ifndef CONFIG_BT_BNEP
#define CONFIG_BT_BNEP 1
#endif /* CONFIG_BT_BNEP */ 
#ifndef CONFIG_BT_BNEP_MC_FILTER
#define CONFIG_BT_BNEP_MC_FILTER 1
#endif /* CONFIG_BT_BNEP_MC_FILTER */ 
#ifndef CONFIG_BT_BNEP_PROTO_FILTER
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#endif /* CONFIG_BT_BNEP_PROTO_FILTER */ 
#if defined(CONFIG_ISDN_CAPI) || defined(CONFIG_ISDN_CAPI_MODULE)
#ifndef CONFIG_BT_CMTP
#define CONFIG_BT_CMTP 1
#endif /* CONFIG_BT_CMTP */ 
#endif /* CONFIG_ISDN_CAPI */
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,28))
#ifndef CONFIG_COMPAT_BT_HIDP
#define CONFIG_COMPAT_BT_HIDP 1
#endif /* CONFIG_COMPAT_BT_HIDP */ 
#endif /* CONFIG_COMPAT_KERNEL_2_6_28 */
#ifndef CONFIG_BT_HCIUART
#define CONFIG_BT_HCIUART "M"
#endif /* CONFIG_BT_HCIUART */ 
#ifndef CONFIG_BT_HCIUART_H4
#define CONFIG_BT_HCIUART_H4 1
#endif /* CONFIG_BT_HCIUART_H4 */ 
#ifndef CONFIG_BT_HCIUART_BCSP
#define CONFIG_BT_HCIUART_BCSP 1
#endif /* CONFIG_BT_HCIUART_BCSP */ 
#ifndef CONFIG_BT_HCIUART_ATH3K
#define CONFIG_BT_HCIUART_ATH3K 1
#endif /* CONFIG_BT_HCIUART_ATH3K */ 
#ifndef CONFIG_BT_HCIUART_LL
#define CONFIG_BT_HCIUART_LL 1
#endif /* CONFIG_BT_HCIUART_LL */ 
#ifndef CONFIG_BT_HCIVHCI
#define CONFIG_BT_HCIVHCI 1
#endif /* CONFIG_BT_HCIVHCI */ 
#ifdef CONFIG_NET_SCHED
#ifdef CONFIG_NETDEVICES_MULTIQUEUE
#ifndef CONFIG_MAC80211_QOS
#define CONFIG_MAC80211_QOS 1
#endif /* CONFIG_MAC80211_QOS */ 
#endif
#endif
#endif /* COMPAT_AUTOCONF_INCLUDED */
